### ISSUE TITLE
Correct wiring U402

### ISSUE THREAD

**Issue by Agilitytime** [hatlabs/SH-ESP32-hardware#50]
Hi Together,

is the wiring here correct?
The connectinon do not have to be between D+ and D-?

Best,
Basti 

![Bildschirmfoto 2021-05-03 um 09 19 28](https://user-images.githubusercontent.com/62443876/116850350-cc1ebf80-abf0-11eb-82a5-ca358a0602f5.png)

**Comment by mairas** [comment]
Hi,

Yes, it's correct. 😊 The ESD protection diode array clamps the input voltage of each connected trace to (roughly) -0.6V and 7.8V, dissipating any static electricity discharges before they can damage the inputs of the protected circuitry. Both D+ and D- are individually protected.

See the datasheet here: https://datasheet.lcsc.com/lcsc/1811061308_BORN-RCLAMP0524P-N_C316044.pdf
