### ISSUE TITLE
RFE: hat with multiple digital and analog inputs 

### ISSUE THREAD

**Issue by mgrouch** [hatlabs/SH-ESP32-hardware#61]
Current implementation of esp32 hat is too generic. There is too much DIY required to 
build a usable device. 

It be nicer if there was esp hat with headers 
for multiple digital and analog inputs. 

Clearly marked like:

tank1,
tank2,
temp1,
temp2,
rpm1,
rpm2,
press1,
press2,
volt1,
volt2 
etc

and generic esp32 firmware with ui (web or LVGL touchscreen) for setting up the sensor readers. 

So end user could just use to set up sensors without need to program esp32. 

Victron Cerbo GX something similar 
for tank level sensors and thermometers. 

just an idea
Thanks!

**Comment by mgrouch** [comment]
![IMG_5583](https://github.com/hatlabs/SH-ESP32-hardware/assets/8263013/4cf47680-bb09-44df-8124-dc955909f011)

Some ideas what inputs can be

**Comment by mairas** [comment]
SH-ESP32 is a developer board, not an end user product. I wish you wouldn't make improvement requests in any of the repos I administer; they are not helpful.
